name: satellite
channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh=2.1.1
  - cartopy=0.18.0
  - celery
  - descartes=1.1.0
  - earthengine-api
  - fiona=1.8.13.post1
  - gdal=3.0.2
  - geopandas=0.8.1
  - geos=3.8.0
  - geotiff=1.5.1
  - geoviews=1.8.1
  - geoviews-core=1.8.1
  - hdf4=4.2.13
  - hdf5=1.10.4
  - holoviews=1.13.3
  - icu=58.2
  - imageio=2.9.0
  - libgdal=3.0.2
  - libxml2=2.9.9
  - netcdf4=1.4.2
  - pip=20.2.2
  - poppler=0.65.0
  - poppler-data=0.4.9
  - postgresql=11.2
  - proj=6.2.1
  - pydrive
  - pyproj=2.6.1.post1
  - python=3.7.7
  - rasterio=1.1.0
  - rasterstats=0.14.0
  - requests=2.25.1
  - scipy=1.5.2
  - urllib3=1.26.2
  - xarray=0.16.0
  - pip:
    - amqp==2.6.1
    - dbfread==2.0.7
    - docker-compose==1.26.2
    - folium==0.11.0
    - geojson==2.5.0
    - odo==0.5.0
    - pytest==6.0.1
    - python-dotenv==0.14.0
    - python-metar==1.4.0
    - responses==0.11.0
    - sqlalchemy
