name: alertacapture
channels:
  - conda-forge
  - defaults
dependencies:
- pip
- pandas
- requests
- flower
- folium
- bokeh
- psycopg2
- pgcli
- geojson
- python-dotenv
- dbfread
- pandasql
- celery
- tornado

- pip:
    - odo
    - pymongo
    - python-metar
    - sqlsoup
    - bearcart
    